name: Lint

on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        with:
          go-version-file: go.mod
          cache: false

      - name: Golangci lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          args: --verbose

      - name: Markdown lint
        uses: docker://avtodev/markdown-lint:v1@sha256:6aeedc2f49138ce7a1cd0adffc1b1c0321b841dc2102408967d9301c031949ee
        with:
          config: '.markdownlint.yml'
          args: '**/*.md'

      - name: Typo lint
        uses: crate-ci/typos@b74202f74b4346efdbce7801d187ec57b266bac8 # v1.27.3
        with:
          config: .typos.toml

      - name: Example lint
        run: make validate-examples

      - name: Run tests
        run: make test
